# Generated by Django 3.1.1 on 2020-09-10 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=100)),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('trim', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=80)),
                ('password', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='SellingFeatures',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feat1', models.CharField(max_length=50)),
                ('feat2', models.CharField(max_length=50)),
                ('feat3', models.CharField(max_length=50)),
                ('feat4', models.CharField(max_length=50)),
                ('feat5', models.CharField(max_length=50)),
                ('feat6', models.CharField(max_length=50)),
                ('feat7', models.CharField(max_length=50)),
                ('feat8', models.CharField(max_length=50)),
                ('feat9', models.CharField(max_length=50)),
                ('feat10', models.CharField(max_length=50, null=True)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='suresell.car')),
            ],
        ),
    ]
